### ISSUE TITLE
TS errors when extending object literal attempts to define/override init

### ISSUE THREAD

**Issue by theseyi** [typed-ember/ember-typings#18]
I have a Ember.Service definition below:
```javascript
import Ember from 'ember';

const { Service } = Ember;

export default Service.extend({
  init() {
    this._super(...arguments);
  }
});
```

However, TypeScript complains that this is incorrect and throw the exception below:
`Error:(6, 3) TS2345:Argument of type '{ init(): void; }' is not assignable to parameter of type 'Mixin'.
  Object literal may only specify known properties, and 'init' does not exist in type 'Mixin'.`

This is supported by the Ember lib and seems like a critical issue

**Comment by theseyi** [comment]
Apologies, this should be raised in @types/ember

**Comment by dwickern** [comment]
This should be fixed by #1 although you can't use `...arguments` due to Microsoft/TypeScript#4384

**Comment by theseyi** [comment]
Hey @dwickern , thanks! Actually just noticed the same issue when switching from `@types/ember` to this. Is there an ETA on when this will get merged and released?

**Comment by theseyi** [comment]
To help anyone else who might come across this in the interim, pending the merge:
 the workaround I implemented was to re-open the the constructor prototype and augment with the init method. So using my example above:
```javascript

const MyService = Service.extend({});

Ember.Object.reopen.call(MyService, {
  init() {
    this._super(...Array.from(arguments));
  }
});
```
even though `reopen` is available on `MyService`, the current typings are also inaccurate there too
