### ISSUE TITLE
`this` context lost in computed getters

### ISSUE THREAD

**Issue by chriskrycho** [typed-ember/ember-typings#47]
I played a little with trying to pass around the `this` context for them, but 😬 that seems like not a lot of fun.

Is our best bet here to lean hard on `@computed`? Can we bind the `this` context there more easily, at least in a class method context?

**Comment by dwickern** [comment]
I believe `@computed() function() { ... }` is the only time typescript can infer the context right now. It won't work in `Ember.computed(function() { ... })`, `function() { ... }.property()`, or computed macros.

You can explicitly type `this` if you're using ES6 classes with some extra boilerplate to work around the circular definition 

> Error:(20, 5) TS7022:'fullName' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.
```ts
class Person extends Ember.Object {
    firstName = '';
    lastName = '';
    fullName = Ember.computed('firstName', 'lastName', function(this: Person) {
        return `${this.get('firstName')} ${this.get('lastName')}`
    })
}
```

Working:
```ts
class Person extends Ember.Object {
    firstName = '';
    lastName = '';
    fullName: Ember.ComputedProperty<string> = Ember.computed('firstName', 'lastName', function(this: Person) {
        return `${this.get('firstName')} ${this.get('lastName')}`
    })
}
```

**Comment by dwickern** [comment]
Here's how the decorator method would work. You do probably need the explicit type annotation since decorators can't contribute to the return type
```ts
class Person extends Ember.Object {
    firstName = '';
    lastName = '';

    @computed('firstName', 'lastName')
    get fullName(): ComputedProperty<string> {
        return `${this.get('firstName')} ${this.get('lastName')}`
    }
}
```

**Comment by chriskrycho** [comment]
Noted. We should document those. _le sigh_ at TS not being able to pull the type back up that way.

**Comment by dwickern** [comment]
Actually you can't even type `fullName` that way since you'll get a type error. You have to lie and say it returns a `string`
