### ISSUE TITLE
Issues with current Route definitions

### ISSUE THREAD

**Issue by chriskrycho** [typed-ember/ember-typings#48]
Using the latest, I bumped into the following issues:

  - `beforeModel` and `afterModel` (a) should be generic and (b) are overly strict. Should *probably* be something like this:

    ```ts
    beforeModel<T>(transition: Transition): Rsvp.Promise<T>;
    beforeModel(transition: Transition): void;
    ```

  - Similarly, `model` should probably be something *like*

    ```ts
    model<T>(params: {}, transition: Transition): T | Rsvp.Promise<T>;
    model(params: {}, transition: Transition): void;
    ```

I also ran into issues with the `ActionsHash` bits combined with the user of `Route.extend(SomeMixin)`, but I strongly suspect the mixin pattern is to blame there, rather than the `Route` definition.

**Comment by dwickern** [comment]
The actual return type would be something like `Promise<any> | any | void`, which reduces to `any`

**Comment by dwickern** [comment]
`ActionsHash` should be fixed in #24

**Comment by chriskrycho** [comment]
🤔 Is there anywhere you'd directly call the hook yourself? I guess not, thinking about it. I was thinking it'd be helpful to be able to define those to work in a specific way so that you'd know whether you were returning what you'd claim. I *think* if it returns `any`, the override a user supplies should be able to be *more* specific, right?

**Comment by dwickern** [comment]
Right, you could have a more specific return type annotation to check that you implemented it correctly.

In practice all my model hooks would return something like `DS.Model | PromiseLike<DS.Model>`, however we can't assume everyone uses E-D
