### ISSUE TITLE
Ember typing issues to fix

### ISSUE THREAD

**Issue by chriskrycho** [typed-ember/ember-typings#69]
I'm in the process of fixing *every* type error in the ~35k lines of TS in our app, and tracking things that need tweaking in the typings from that or that get flagged up in Slack here.

## Ember.js

- [x] `Mixin` needs to support multiple arguments to `create`. Something *roughly* like this (and out to *several*):
    ```ts
    static create<T1, T2, Base = Ember.Object>(
      arg1: T1 & ThisType<Fix<T1 & Base>>,
      arg2: T2 & ThisType<Fix<T2 & Base>>
    ): Mixin<T1 & T2, Base>;
    ```
- [x] `Mixin`  needs to have `__ember_mixin__` not be private.
- [x] `Route#afterModel` and `Route#beforeModel` should return `any` since `any | Promise<any>` just reduces to `any`.
- [x] `Route#serialize` should return `object`
- [x] computed property macros
    - [x] `or` should return `ComputedProperty<boolean>`
    - [x] `and` should return `ComputedProperty<boolean>`

## ember-data

- [x] use `RSVP.Promise` not native `Promise`
- [x] `Store#adapterFor` needs to be generic over `A extends Adapter`
- [x] `Store#serializerFor` needs to be generic over `S extends Serializer`
- [x] `Model#serialize`'s `options` param should be optional

## ember-qunit

- [x] `QUnitModuleCallbacks` needs `needs?: string[]`

**Comment by chriskrycho** [comment]
Closing this as done in light of the aforelinked Definitely Typed PR.

**Comment by chriskrycho** [comment]
Found a couple more!

- [ ] `buildUrl` arguments other than `modelName` should be optional
    - [ ] on `RESTAdapter`
    - [ ] on `BuildURLMixin`

**Comment by tansongyang** [comment]
Linking to https://github.com/DefinitelyTyped/DefinitelyTyped/pull/22543
