### ISSUE TITLE
cannot find module '@ember/error'

### ISSUE THREAD

**Issue by ggayowsky** [typed-ember/ember-typings#71]
typescript complains when trying to import the `@ember/error` module.

**Comment by chriskrycho** [comment]
@ggayowsky sorry for the delay, as I’ve been going after other pieces of this stuff. I’ll try to take a look in the next week or so.

**Comment by chriskrycho** [comment]
Hi @ggayowsky, sorry it took so long for one of us get back to this! I've opened a PR to fix it [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24545); hopefully it'll be resolved in the next couple days! I'll close this issue once that's merged.

**Comment by chriskrycho** [comment]
Resolved! Should be able to pull an update that has this shortly!
