### ISSUE TITLE
Using ES classes with Route, model, and async

### ISSUE THREAD

**Issue by cptran777** [typed-ember/ember-typings#72]
Hey everyone! 

I ran into an issue when using ES classes and trying to use async/await on the Route's model hook. Use case is below:
```
class MyRoute extends Route {
  async model(): Promise<any> {
    const prop = await this.get('store').findRecord('someRecord', 'someParam');
    return { prop };  
  }
}
```

However, the above would through the following error
```
Class 'MyRoute' incorrectly extends base class 'Route'.
  Types of property 'model' are incompatible.
    Type '() => Promise<any>' is not assignable to type '<T>(params: {}, transition: Transition) => T | Promise<T>'.
      Type 'Promise<any>' is not assignable to type 'T | Promise<T>'.
        Type 'Promise<any>' is not assignable to type 'Promise<T>'.
          Property 'new' is missing in type 'Promise<any>'.
```

I'm assuming because the definition of model() in Route is expected to return `T | Promise<T>` However, if you try to change the return type for the above to 
```
async model(): any | Promise<any>
```
Then you lose the above error for Route and get one for async instead:
```
[ts] The return type of an async function or method must be the global Promise<T> type.
```

Was wondering if this is an issue that should be fixed or if there is some insight that I'm missing. Thanks!

**Comment by dwickern** [comment]
The return type for `Route#model()` should be fixed now. Try updating your `@types/ember`.

**Comment by chriskrycho** [comment]
Can confirm that this error is resolved on latest `@types/ember`, as I'd had it previously and it went away after we updated. Closing accordingly (though feel free to comment again and I'll reopen if it doesn't for some reason).
