### ISSUE TITLE
Wrong typing for `this.addObserver` in a component

### ISSUE THREAD

**Issue by gossi** [typed-ember/ember-typings#76]
Here is a little snippet:

```ts
import Component from '@ember/component';

export default class MyComponent extends Component {

	view: string = 'list';

	constructor() {
		super(...arguments);

		this.addObserver('view', () => {
			this.doSomething();
		});
	}
}
```

Now, typescript will report `Expected 3 arguments, but got 2` for the `addObserver` method. However, this code is absolutely fine. May be that ember itself isn't clear about their method signatures on that case.

Here is the code trace to this:

1. `Component` extends `CoreView` extends `CoreObject` which includes the mixin `Observable`
2. `Observable.addObserver` is defined here https://github.com/emberjs/ember.js/blob/3a4b38000b2cc3ce49d93f4df45415db545b3752/packages/ember-runtime/lib/mixins/observable.js#L353 and passes it down to `addObserver` from `ember-metal`
3. Here is `addObserver` at `ember-metal` https://github.com/emberjs/ember.js/blob/3a4b38000b2cc3ce49d93f4df45415db545b3752/packages/ember-metal/lib/observer.js#L23 which passes it down to `addListener`
4. Here is `addListener` with the code line that says, the third argument is optional: https://github.com/emberjs/ember.js/blob/3a4b38000b2cc3ce49d93f4df45415db545b3752/packages/ember-metal/lib/events.js#L60

Here is the relevant typing to that (if I'm correct): https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e22846ad77459b3ece25598db93c2013e8c76716/types/ember/index.d.ts#L1683

I would have fixed this on my own, but these typings look like perl to me (😂).

**Comment by chriskrycho** [comment]
Thank you! You should be able to submit a PR to DefinitelyTyped with the typing changed like this:

```diff
            addObserver<Target>(
                key: keyof this,
                target: Target,
-               method: ObserverMethod<Target, this>
+               method?: ObserverMethod<Target, this>
            ): void;
```

It'd be good to add a test to the test suite there as well. If you open a PR over there we'll be happy to help coach through to getting it merged!

**Comment by gossi** [comment]
That's already fixed :) closing
