### ISSUE TITLE
htmlSafe() has no return type but is SafeString

### ISSUE THREAD

**Issue by gossi** [typed-ember/ember-typings#77]
Just discovered: `htmlSafe(): void` but instead should be `htmlSafe(): SafeString` see: https://github.com/emberjs/ember.js/blob/ab975417c47d49cd183b1e0470aea3c77c162682/packages/ember-glimmer/lib/utils/string.ts#L78-L85

**Comment by chriskrycho** [comment]
Nice catch! Mind opening a PR with that change on DefinitelyTyped?

**Comment by gossi** [comment]
Sure. I just posted it here, so I didn't forget it 😂 Will come back to it, when I finished some other things that have higher prio 😉

**Comment by chriskrycho** [comment]
Closed in favor of typed-ember/ember-cli-typescript#232.
